/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'id' : bigint,
  'isInvoiced' : boolean,
  'owner' : Principal,
  'details' : string,
}
export interface Invoice {
  'id' : bigint,
  'status' : string,
  'projectName' : string,
  'clientName' : string,
  'owner' : [] | [Principal],
  'dueDate' : string,
  'payerSource' : string,
  'amountDue' : number,
}
export interface LOCInquiry {
  'client' : string,
  'statementPeriod' : string,
  'mrNumber' : string,
  'payer' : string,
  'amount' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInquiry' : ActorMethod<[string], bigint>,
  /**
   * / --- Invoice Management
   * / Create invoice (can be anonymous for LOC, otherwise must be logged in)
   */
  'createInvoice' : ActorMethod<
    [string, number, string, string, string],
    bigint
  >,
  /**
   * / Delete Invoice - supports anonymous invoices (LOC) deletion without authentication
   */
  'deleteInvoice' : ActorMethod<[bigint], boolean>,
  'displayLOCInquiry' : ActorMethod<[], [] | [LOCInquiry]>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoicesByClient' : ActorMethod<[string], Array<Invoice>>,
  'getInvoicesByStatus' : ActorMethod<[string], Array<Invoice>>,
  'getLOCReceivables' : ActorMethod<[], Array<Invoice>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markInquiryAsInvoiced' : ActorMethod<[bigint, boolean], boolean>,
  'markInvoiceAsPaid' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];